import React from 'react';

const LegalLayout = ({ title, lastUpdated, children }: { title: string, lastUpdated: string, children: React.ReactNode }) => (
  <div className="pt-10 pb-48 px-6 max-w-4xl mx-auto">
    <div className="mb-20 space-y-4">
      <div className="text-xs font-black text-primary uppercase tracking-widest">Legal & Governance</div>
      <h1 className="text-5xl md:text-6xl font-black text-on-surface tracking-tighter">{title}</h1>
      <p className="text-secondary font-medium italic">Last Updated: {lastUpdated}</p>
    </div>
    <div className="prose prose-slate max-w-none 
      prose-h2:text-2xl prose-h2:font-black prose-h2:text-on-surface prose-h2:mt-12 prose-h2:mb-6 
      prose-p:text-lg prose-p:text-secondary prose-p:leading-relaxed prose-p:mb-6
      prose-li:text-lg prose-li:text-secondary prose-li:mb-2 prose-ul:mb-8">
      {children}
    </div>
  </div>
);

export const Privacy: React.FC = () => (
  <LegalLayout title="Privacy Policy" lastUpdated="October 15, 2025">
    <h2>1. Data We Collect</h2>
    <p>As an authentication provider, we collect minimal information necessary to secure your users' identity. This includes:</p>
    <ul>
      <li>User identifiers (email, handle, or unique ID provided by you)</li>
      <li>Security telemetry (IP address, device metadata for threat detection)</li>
      <li>Usage logs for billing and performance monitoring</li>
    </ul>
    <h2>2. Zero-Knowledge Principles</h2>
    <p>Our infrastructure is built so that we do not have access to raw user passwords or biometric data. Biometric authentication is handled by the local device enclave (TouchID, FaceID, Windows Hello), and we only verify the cryptographic proof generated by that enclave.</p>
    <h2>3. Data Transfer</h2>
    <p>Your data is stored in our global edge network. By using our services, you consent to the transfer of information between our various regional nodes to ensure low-latency authentication.</p>
  </LegalLayout>
);

export const Terms: React.FC = () => (
  <LegalLayout title="Terms of Service" lastUpdated="October 15, 2025">
    <h2>1. Acceptance of Terms</h2>
    <p>By integrating the TaskAPI SDK or utilizing our REST endpoints, you agree to be bound by these institutional terms of service.</p>
    <h2>2. API Usage & Rate Limits</h2>
    <p>Standard clusters are subject to rate limiting to protect the integrity of the network. Enterprise customers with dedicated clusters are bound by their specific Service Level Agreements (SLAs).</p>
    <h2>3. Prohibited Use</h2>
    <p>You may not use TaskAPI for any service that involves illegal activities, credential harvesting for third-party platforms, or any action that violates the security of others.</p>
  </LegalLayout>
);

export const Cookies: React.FC = () => (
  <LegalLayout title="Cookie Policy" lastUpdated="October 15, 2025">
    <h2>1. Strictly Necessary Cookies</h2>
    <p>TaskAPI uses essential cookies to maintain security sessions and prevent CSRF attacks. These cannot be disabled as they are fundamental to the authentication handshake.</p>
    <h2>2. Performance Cookies</h2>
    <p>We use localized session markers to route your requests to the nearest edge node, ensuring minimum authentication latency.</p>
  </LegalLayout>
);
